### ISSUE TITLE
[TTIOLT] Oltima 2000 - Crashes 5 seconds after MBBSemu starts up (and is ready for connections)

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#108]
**Module Information**
* Identifier: TTIOLT
* Module Name: Oltima 2000
* Version: unknown

**Describe the bug**
Module initializes and loads, upon entrance the game freezes

**To Reproduce**
1. Load Module
2. Wait 5 seconds after MBBSEmu is ready for connections
3. Get Error

**Expected behavior**
Game is able to play

**Screenshots**
```
2020-09-14 20:18:58.2790 Info MBBSEmu.HostProcess.MbbsHost.AddModule Module TTIOLT added!
2020-09-14 20:18:58.3018 Info MBBSEmu.Program.Run Telnet listening on port 31336
2020-09-14 20:18:58.3018 Info MBBSEmu.Program.Run Rlogin listening on port 31337
2020-09-14 20:18:58.3018 Info MBBSEmu.Program.Run Rlogin TTIOLT listening on port 31338
2020-09-14 20:18:58.3018 Info MBBSEmu.Program.Run Started MBBSEmu Build #091420-5

Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unsupported OpCode: Fsubr')
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()
```

**Software Information:**
- OS: Windows 2019 Server Standard
- Telnet Client: NetRunner

**Comment by tuday2** [comment]
Update -- with Build 091420-5 now crashes upon startup after about 5 seconds::

```
2020-09-14 20:18:58.2790 Info MBBSEmu.HostProcess.MbbsHost.AddModule Module TTIOLT added!
2020-09-14 20:18:58.3018 Info MBBSEmu.Program.Run Telnet listening on port 31336
2020-09-14 20:18:58.3018 Info MBBSEmu.Program.Run Rlogin listening on port 31337
2020-09-14 20:18:58.3018 Info MBBSEmu.Program.Run Rlogin TTIOLT listening on port 31338
2020-09-14 20:18:58.3018 Info MBBSEmu.Program.Run Started MBBSEmu Build #091420-5

Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unsupported OpCode: Fsubr')
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by enusbaum** [comment]
Same as #125

**Comment by enusbaum** [comment]
Leaving this open for now to verify the fix.
