### ISSUE TITLE
[ELWIC] Infinity Complex - Crashes on initialization

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#109]
**Module Information**
* Identifier:  [e.g. *TSGARN*]
* Module Name: Infinity Complex
* Version: 6.04

**Describe the bug**
Game crashes on initialization

**To Reproduce**
1. Add game to modules.json
2. Launch MBBSemu

**Expected behavior**
Infinity Complex initializes

**Screenshots**
```
Critical Exception has occurred:
System.ArgumentException: An item with the same key has already been added. Key: 0100:976B
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.SetupGENBB()
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.MbbsHost.PatchRelocation(MbbsModule module)
   at MBBSEmu.HostProcess.MbbsHost.AddModule(MbbsModule module)
   at MBBSEmu.Program.Run(String[] args)
```

**Software Information:**
- OS: Windows 2019 Server Standard
- Telnet Client: NetRunner

**Comment by tuday2** [comment]
Wheel Of Fame crashes with the same error:

Critical Exception has occurred:
System.ArgumentException: An item with the same key has already been added. Key: 0100:976B
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.SetupGENBB()
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.MbbsHost.PatchRelocation(MbbsModule module)
   at MBBSEmu.HostProcess.MbbsHost.AddModule(MbbsModule module)
   at MBBSEmu.Program.Run(String[] args)

**Comment by tuday2** [comment]
Opened in error, problem with install
