### ISSUE TITLE
[MJWWHL] Wheel of Fame - Crashes when starting a game "play"

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#111]
**Module Information**
* Identifier: MJWWHL
* Module Name: Wheel of Fame
* Version: Unknown

**Describe the bug**
Game crashes when starting a round with "play"

**To Reproduce**
1. Load module
2. Start a game "play"
3. After multiplier is given game crashes

**Expected behavior**
Able to play Wheel of Fame

**Screenshots**
![Screenshot 2020-09-11 214511](https://user-images.githubusercontent.com/27604078/92985438-1e4f7c80-f478-11ea-9f9e-3734fd399a7f.JPG)

```
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key '65535' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.outprf()
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.CPU.CpuCore.Tick()
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: NetRunner

**Comment by tuday2** [comment]
Duplicate.
