### ISSUE TITLE
[ELWCRAPS] Craps! - Crashes after entering the amount of your bet

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#114]
**Module Information**
* Identifier: ELWCRAPS
* Module Name: Craps!
* Version: 1.0

**Describe the bug**
Crashes after entering the amount of your bet

**To Reproduce**
1. Enter CRAPS module
2. Select (P) "Play Craps"
3. Enter # of credits to bet

**Expected behavior**
Able to make a bet and play craps

**Screenshots**
![Screenshot 2020-09-11 233601](https://user-images.githubusercontent.com/27604078/92987393-95d8d800-f487-11ea-8723-98bd1478bfef.JPG)

```
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unknown Exported Function Ordinal in MAJORBBS: 517')
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.CPU.CpuCore.Tick()
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: NetRunner

**Comment by enusbaum** [comment]
`MAJORBBS.517` is `RTSTCRD` -- `int enuf=rtstcrd(long amount);`

![image](https://user-images.githubusercontent.com/1139047/93027239-9f725500-f5d9-11ea-9866-560b0fa95986.png)
