### ISSUE TITLE
[ELWFOUR] FOURmation - Game crashes when challenging another player to a game

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#117]
**Module Information**
* Identifier: ELWFOUR
* Module Name: FOURmation
* Version: 2.00

**Describe the bug**
Game crashes when entering a game against an opponent

**To Reproduce**
1. Enter module
2. Challenge a player to a game (option 1)

**Expected behavior**
Ability to play FOURmation game

**Screenshots**
![Screenshot 2020-09-12 080122](https://user-images.githubusercontent.com/27604078/92996075-3d78f900-f4ce-11ea-9bbc-c8f033ec7f94.JPG)

```
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unknown Exported Function Ordinal in MAJORBBS: 449')
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.CPU.CpuCore.Tick()
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Software Information:**
- OS: Windows 2019 Server Standard
- Telnet Client: NetRunner

**Comment by enusbaum** [comment]
`MAJORBBS.449` is `ONSYS` -- `int ison=onsys(char *usrid);`

Determines if the given user/screen name is online or not. Returns `1` if the user is online
