### ISSUE TITLE
[ELWGOLF] Electronic Fairways - Module crashes during gameplay

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#118]
**Module Information**
* Identifier: ELWGOLF
* Module Name: Electronic Fairways
* Version: 2.0

**Describe the bug**

**To Reproduce**
1. Enter Module
2. (P)lay Game
3. Select club and strength

**Expected behavior**
Ability to play through a shot

**Screenshots**
![Screenshot 2020-09-12 081948](https://user-images.githubusercontent.com/27604078/92996391-e163a400-f4d0-11ea-963b-04ef882e2b22.JPG)

```
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unsupported OpCode: Fdivp')
   at MBBSEmu.CPU.CpuCore.Tick()
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Software Information:**
- OS: Windows 2019 Server Standard
- Telnet Client: NetRunner

**Comment by enusbaum** [comment]
`FDIVP` - Similar to `FADDP`. Divide ST(1) by ST(0), store result in ST(1), and pop the register stack effectively making the result stored in ST(1) now ST(0).

**Comment by tuday2** [comment]
Getting this error now -- is this related or a new issue? @enusbaum @paladine 

Unhandled exception. System.Exception: Type Requested not UInt16
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
