### ISSUE TITLE
[WCCMMUD] MajorMud - Game Crashes when editing Sysop Bulletin

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#125]
**Module Information**
* Identifier: WCCMMUD
* Module Name: MajorMud
* Version: 1.11g

**Describe the bug**
Try to edit Sysop Bulletin and game crashes

**To Reproduce**
1. Drop in generic ANSI file and name WCCSYSOP.BUL in MAJORMUD module directory
2. Enter MajorMud module
3. Enter "SYSOP" for sysop commands
4. Select "B" to edit Sysop Bulletin
5. See Error

**Expected behavior**
Edit ANSI file

**Screenshots**
```
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unsupported OpCode: Fsubr')
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()
```

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: NetRunner

**Comment by enusbaum** [comment]
Missing `FSUBR` OpCode

https://www.felixcloutier.com/x86/fsubr:fsubrp:fisubr

**Comment by tuday2** [comment]
**Error now:**

Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unable to locate FFFF:04A7')
   at MBBSEmu.Memory.MemoryCore.GetArray(UInt16 segment, UInt16 offset, UInt16 count)
   at MBBSEmu.Memory.MemoryCore.GetPointer(UInt16 segment, UInt16 offset)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by tuday2** [comment]
@enusbaum @paladine  Please reopen issue (I don't think I have permission)
