### ISSUE TITLE
[ELWMAN] Mancala - Crashes when starting game with another player

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#128]
**Module Information**
* Identifier: ELWMAN
* Module Name: Mancala
* Version 1,21

**Describe the bug**
Game crashes when accepting a challenge of another player

**To Reproduce**
1. Enter Mancala module (both players)
2. Challenge another player to a game
3. Accept challenge

**Expected behavior**
Able to play game of Mancala

**Screenshots**
```
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key '1283' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MBBSEmu.Memory.MemoryCore.GetInstruction(UInt16 segment, UInt16 instructionPointer)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()
```

**Software Information:**
- OS: Windows 2019 Server Standard
- Telnet Client: NetRunner

**Comment by enusbaum** [comment]
Similar to #129 -- an Opcode is causing a jump to an invalid instruction pointer

**Comment by tuday2** [comment]
Fixed.
