### ISSUE TITLE
[ELWSS] Sub Striker - MBBSEmu crashes when connecting 

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#135]
**Module Information**
* Identifier: ELWSS
* Module Name: Sub Striker
* Version: 1.03b

**Describe the bug**
MBBSEmu crashes when connecting to telnet (only 1 module loaded)

**To Reproduce**
1. Add module to moduleConfig.json
2. Load MBBSEmu
3. Connect to telnet port

**Expected behavior**
Module loads and able to connect to BBS

**Screenshots**
```
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unable to locate FFFF:02E1')
   at MBBSEmu.Memory.MemoryCore.GetWord(UInt16 segment, UInt16 offset)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Software Information:**
- OS: Windows 2019 Server Standard
- Telnet Client: NetRunner

**Comment by enusbaum** [comment]
Ordinal `MAJORBBS.737` is `_8087` which looks to signal to the program if an x87 math co-processor is present. 

![image](https://user-images.githubusercontent.com/1139047/93596485-634b4580-f987-11ea-99fa-5d100aa7d408.png)

In this case, it appears we can return a constant of `3` to denote the presence of an x87 FPU and process the FPU command `FCOS` normally.
