### ISSUE TITLE
[ELWNS] Number Shuffle - Crashes on Initialization

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#136]
**Module Information**
* Identifier: ELWNS
* Module Name: Number Shuffle
* Version: 1.0

**Describe the bug**
Module crashes on initialization

**To Reproduce**
1. Add module to moduleConfig.json
2. Start MBBSEmu
3. See error

**Expected behavior**
Module loads

**Screenshots**
```
Critical Exception has occurred:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unknown Exported Function Ordinal in MAJORBBS: 996')
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.AddModule(MbbsModule module)
   at MBBSEmu.Program.Run(String[] args)
```

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: NetRunner

**Comment by enusbaum** [comment]
Ordinal `MAJORBBS.996` is `getbtvl()` which is the same (essentially) get `getbtv()` but denotes that it's a variable length record "get". Because MajorBBS btrieve files don't use variable record length, we can implement this similar to `getbtv()`

`void getbtvl (void *recptr, void *key, int keynum, int getopt, int loktyp);`
