### ISSUE TITLE
[ELWPIG] Pig! - Crashes on Entry

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#137]
**Module Information**
* Identifier: ELWPIG
* Module Name: Pig!
* Version: 1.01

**Describe the bug**
Module crashes on entry

**To Reproduce**
1. Add module to moduleConfig.json
2. Start MBBSEmu
3. Enter mdoule

**Expected behavior**
Module loads

**Screenshots**
### OLD ERROR
```
Critical Exception has occurred:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unknown Exported Function Ordinal in MAJORBBS: 203')
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.AddModule(MbbsModule module)
   at MBBSEmu.Program.Run(String[] args)
```
### NEW ERROR
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at MBBSEmu.Btrieve.BtrieveFileProcessor.GetRecordByOffset(UInt32 absolutePosition)
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.gabbtv()
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.CPU.CpuCore.Op_Call()
   at MBBSEmu.CPU.CpuCore.Tick()
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: NetRunner
- MBBSEmu Build: 110720-12

**Comment by enusbaum** [comment]
Ordinal `MAJORBBS.203` is `FARMALLOC`, which denotes an allocation in far memory. The catch here is that the allocation is a `ulong` for size. 

We'll need to look into how this works, because while it looks similar to how Big Memory allocation already works, we'll need to figure out how it handles windowing as the max offset for the pointer will be ushort.

**Comment by tuday2** [comment]
Error message has changed in latest build, sounds btrieve related now - gabbtv()

**Comment by paladine** [comment]
Game works fine now.
