### ISSUE TITLE
[ELWSWAR] Strategic War Games - Crashes when entering module

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#138]
**Module Information**
* Identifier:  ELWSWAR
* Module Name: Strategic War Games
* Version: 1.05

**Describe the bug**
Crashes when entering module

**To Reproduce**
1. Add module to moduleConfig.json
2. Load MBBSEmu
3. Login and enter module

**Expected behavior**

**Screenshots**
```
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unknown Exported Function Ordinal in MAJORBBS: 137')
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()
```

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: NetRunner

**Comment by enusbaum** [comment]
Ordinal `MAJORBBS.137` is `condex()` which specifies a conditional module exit. 

We'll need to research how this ordinal operates.

**Comment by tuday2** [comment]
Based on this we may just need to set a flag since we would never use this functionality -- I don't think

![CONDEX](https://user-images.githubusercontent.com/27604078/97484416-b9b48800-1926-11eb-938b-c9b892460757.jpg)

**Comment by tuday2** [comment]
v6 btrieve game, not designed for dos mbbs
