### ISSUE TITLE
[MJWMUT] Mutants! - Crashes when you load a registered copy of Mutants!

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#146]
**Module Information**
* Identifier: [MJWMUT]
* Module Name: Mutants!
* Version: 3.11

**Describe the bug**
Crashes when you load a registered copy of Mutants!

**To Reproduce**
1. Add Mutants to moduleConfig.json and valid reg code to .msg file
2. Load MBBSEmu
3. See error

**Expected behavior**
Game loads normally

**Screenshots**
```
Critical Exception has occurred:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unknown Exported Function Ordinal in MAJORBBS: 432')
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.AddModule(MbbsModule module)
   at MBBSEmu.Program.Run(String[] args)
```

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: Netrunner

**Comment by enusbaum** [comment]
Ordinal `MAJORBBS.432` is `NKYREC` 

`void nkyrec(char *uid);`

Looking at how it's used, this appears to create an empty key record in the user keys Btrieve File (`BBSK.DAT`). Looking at `BBSK.DAT` it appears the only key defined is the 30-character username. 

![image](https://user-images.githubusercontent.com/1139047/94341211-97e97d80-ffd5-11ea-8279-5133d94adf12.png)

Currently MBBSEmu returns `TRUE` for any key. We can probably stub this function out for the time being, but if we want to really enforce lock/key mechanics the same as MajorBBS/Worldgroup, we probably want to track these keys in the internal SQLite `AccountKey` table and have key verifications work from there.
