### ISSUE TITLE
Mutants! - Missing API (MAJORBBS.51 - AABBTV)

### ISSUE THREAD

**Issue by enusbaum** [enusbaum/MBBSEmu#15]
An exception is thrown in Mutants! when a creature kills another creature.

```
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unknown Exported Function Ordinal in MAJORBBS: 51')
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.CPU.CpuCore.Tick()
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

This exception is due to missing API MAJORBBS.51 - `AABBTV`

`int aabbtv (void *recptr, long abspos, int keynum);`

![image](https://user-images.githubusercontent.com/1139047/90200917-585d2e00-dda7-11ea-8410-c7e8650e24e4.png)

**Comment by enusbaum** [comment]
Verified working in 3f3037842e1e7cef4115fe5c953e381543e328f2

Waiting for Tester verification before closing 👍

**Comment by enusbaum** [comment]
Confirmed Fixed!
