### ISSUE TITLE
[ELWBAK] Pro Backgammon - Module crashes when entering from menu

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#156]
**Module Information**
* Identifier: ELWBAK
* Module Name: Pro Backgammon
* Version: 3.06

**Describe the bug**
Crashes on selection from menu

**To Reproduce**
1. Add Pro Backgammon module to config
2. Start MBBSemu
3. Select menu item for Pro Backgammon

**Expected behavior**
Module runs without crashing

```
2020-10-04 21:27:16.4684 Error MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke Unknown Exported Function Ordinal in MAJORBBS: 960:STP4CS
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unknown Exported Function Ordinal in MAJORBBS: 960:STP4CS')
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: Netrunner

**API REPORT**
{"UniqueIdentifier":"ELWbak","File":"ELWBAK.DLL","Imports":{"DOSCALLS":[89],"PHAPI":[16],"MAJORBBS":[629,534,543,783,785,628,786,484,520,624,999,53,485,880,162,330,561,599,566,455,492,589,331,550,559,601,357,757,574,997,456,350,401,403,571,578,568,521,762,761,463,474,77,467,625,107,650,441,879,437,475,510,85,476,411,119,117,351,428,787,458,713,654,659,486,604,587,377,621,661,657,134,157,580,640,639,582,779,827,788,712,505,511,335,726,459,409,560,665,522,974,941,942,938,927,1170,68,930,996,968,943,1144,944,973,960,958,572,967,940,1172,1171,326,348,460,449,167],"GALGSBL":[40,30,53,36,72]}}

**Comment by tuday2** [comment]
Duplicate
