### ISSUE TITLE
[ELWSS] Sub Striker - MBBSEmu crashes around 10 seconds after loading MBBSEmu

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#159]
**Module Information**
* Identifier: ELWSS
* Module Name: Sub Striker
* Version: 1.03b

**Describe the bug**
MBBSEmu crashes after 10 seconds (only module loaded)

**To Reproduce**
1. Add module to moduleConfig.json
2. Load MBBSEmu
3. Wait around 10 seconds

**Expected behavior**
Module loads and able to connect to BBS

**Screenshots**
```
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unable to locate FFFF:02E1')
   at MBBSEmu.Memory.MemoryCore.GetWord(UInt16 segment, UInt16 offset)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Software Information:**
- OS: Windows 2019 Server Standard
- Telnet Client: NetRunner
- MBBSEmu: Build #100220-5

**Comment by enusbaum** [comment]
This is a bug -- and my bad. `_8087` was implemented in #149 but it was implemented as a method, when it should have been implemented as a value. We need to change this to have a declared memory address with the value `3` set at the address.
