### ISSUE TITLE
[ELWSAFE] Safe Cracker - Module crashes when entering

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#160]
**Module Information**
* Identifier: ELWSAFE
* Module Name: Safe Cracker
* Version: 1.1

**Describe the bug**
Module crashes when entering

**To Reproduce**
1. Add to moduleConfig.json
2. Start MBBSEmu
3. Enter module from menu

**Expected behavior**
Ability to enter module and play game

**Screenshots**
```
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key '65535' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MBBSEmu.Memory.MemoryCore.GetInstruction(UInt16 segment, UInt16 instructionPointer)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: NetRunner
- MBBSEmu Build: 100220-5

**Comment by enusbaum** [comment]
I was unable to replicate this issue using the latest build in Master:

![image](https://user-images.githubusercontent.com/1139047/95088166-96643780-06f0-11eb-9f56-911b6099e7bf.png)

![image](https://user-images.githubusercontent.com/1139047/95088201-a3812680-06f0-11eb-9dc7-d13826464ac0.png)

**Comment by tuday2** [comment]
Deleted *.emu, and bbsgen/bbsusr, mbbsemu.db and now works fine. False Alarm!
