### ISSUE TITLE
[ELWNS] Number Shuffle - Crashes on creating board (2nd step of a game)

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#161]
**Module Information**
* Identifier: ELWNS
* Module Name: Number Shuffle
* Version: 1.0

**Describe the bug**
Crashes on creating board (2nd step of a game)

**To Reproduce**
1. Add module to moduleConfig.json
2. Start MBBSEmu
3. Enter game and select size of grid
3. See error

**Expected behavior**
Able to play Number Shuffle

**Screenshots**
```
Unhandled exception. System.DivideByZeroException: Attempted to divide by zero.
   at System.Math.DivRem(Int32 a, Int32 b, Int32& result)
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.f_ldiv()
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
![Screenshot 2020-10-04 215627-222](https://user-images.githubusercontent.com/27604078/95036095-7ef36300-068c-11eb-93c5-665897eee37c.jpg)

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: NetRunner
- MBBSEmu Build: 100220-5

**Comment by tuday2** [comment]
This is also a problem in Ringmasters when viewing top score

**Comment by enusbaum** [comment]
We need to add Divide By 0 checking to the Exported Ordinal `F_LDIV` in `MAJORBBS`

**Comment by tuday2** [comment]
WG3 module, not compatible.
