### ISSUE TITLE
[CHRGAME] The Lost Caverns of Miczyk - Crashes when creating room

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#166]
**Module Information**
* Identifier: CHRGAME
* Module Name: The Lost Caverns of Miczyk
* Version: ?

**Describe the bug**
Crash when creating room (entering name of room)

**To Reproduce**
1. Enter module
2. Create Character
3. Create room exits, enter room name

**Expected behavior**
Room creates normally

**Screenshots**
```
2020-10-05 21:57:45.3567 Error MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke Unknown Exported Function Ordinal in MAJORBBS: 88:OLDBGNEDT
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unknown Exported Function Ordinal in MAJORBBS: 88:OLDBGNEDT')
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()
```

![Screenshot 2020-10-05 220022-333](https://user-images.githubusercontent.com/27604078/95153916-3c965880-0756-11eb-9f67-47e5c9d927d6.jpg)

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: NetRunner
- MBBSEmu Build: 100220-5

**Comment by enusbaum** [comment]
Ordinal `MAJORBBS.88` is `OLDBGNEDT`, which looks like a proxy API which looks like it calls the Full-Screen Editor (`BGNEDT`)?

We'll need to figure out how the values passed into `OLDBGNEDT` map to `BGNEDT`

**Comment by tuday2** [comment]
Excalibur! and Dialchat both have crashes related to Ordinal 88 #278
