### ISSUE TITLE
[ELWGOLF] Electronic Fairways - Putting crashes module, and math seems off on swings

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#171]
**Module Information**
* Identifier: ELWGOLF
* Module Name: Electronic Fairways
* Version: 2.0

**Describe the bug**
Putting crashes module, and math seems off on swings ("Your shot went 3 yards") -- which is the same distance to the cup ?

**To Reproduce**
1. Enter Module
2. (P)lay Game
3. Select club and strength, Pick Club, Select Strength, Select Putt Strength 

**Expected behavior**
Ability to play through a shot

**Screenshots**
```
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unsupported OpCode: Fsubrp')
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

![Screenshot 2020-10-07 095416-999](https://user-images.githubusercontent.com/27604078/95347948-1de1b000-0883-11eb-9a88-d0cde34f9d0b.jpg)

**Software Information:**
- OS: Windows 2019 Server Standard
- Telnet Client: NetRunner

**Comment by enusbaum** [comment]
Need to add the opcode `FSUBRP` and finish writing Unit Tests for all the remaining Floating Point operations
