### ISSUE TITLE
[ELWSS] Sub Striker - MBBSEmu crashes after 10 seconds (only module loaded)

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#174]
**Module Information**
* Identifier: ELWSS
* Module Name: Sub Striker
* Version: 1.03b

**Describe the bug**
MBBSEmu crashes after 10 seconds (only module loaded)

**To Reproduce**
1. Add module to moduleConfig.json
2. Load MBBSEmu
3. Wait around 10 seconds

**Expected behavior**
Module loads and able to connect to BBS

**Screenshots**
```
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unsupported OpCode: Fsin')
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Software Information:**
- OS: Windows 2019 Server Standard
- Telnet Client: NetRunner
- MBBSEmu: Build: 100720-7

**Comment by enusbaum** [comment]
Need to implement the x87 Opcode `FSIN`

<img width="1135" alt="Screen Shot 2020-10-10 at 8 34 41 PM" src="https://user-images.githubusercontent.com/1139047/95667733-0d0d9480-0b38-11eb-9450-9b8f1006e5ec.png">
