### ISSUE TITLE
[EWEPNT] Phantasia - Crashes entering world - after character creation

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#176]
**Module Information**
* Identifier: EWEPNT
* Module Name: Phantasia
* Version: (C)1995

**Describe the bug**
Crashes entering world - after character creation

**To Reproduce**
1. Load Module
2. Enter Module
3. Create Character

**Expected behavior**
Ability to create character and enter world

**Screenshots**
```
2020-10-07 22:33:56.9405 Warn MBBSEmu.HostProcess.ExportedModules.Majorbbs.prfmsg prfmsg() unable to locate message number 1965 in current MCV file EWEPNT.MCV
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unsupported OpCode: Fdivrp')
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()
```

![Screenshot 2020-10-07 223736-111](https://user-images.githubusercontent.com/27604078/95412079-bca2f680-08ed-11eb-89b8-7203a39e2544.jpg)

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: NetRunneer
- MBBSEmu Build: 100720-7

**Comment by enusbaum** [comment]
This MIIIIGHT be caused by something weird going on in the MSG parser. We'll need to verify the resulting MCV file to see if an escape sequence isn't being handled properly.

**Comment by paladine** [comment]
The missing `Fdivrp` ordinal seems more pertinent here

**Comment by enusbaum** [comment]
🤦 missed that! hahaha
