### ISSUE TITLE
[ELWBAK] Pro Backgammon - Crashes on selection from menu

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#179]
**Module Information**
* Identifier: ELWBAK
* Module Name: Pro Backgammon
* Version: 3.06

**Describe the bug**
Crashes on selection from menu

**To Reproduce**
1. Add Pro Backgammon module to config
2. Start MBBSemu
3. Select menu item for Pro Backgammon

**Expected behavior**
Module runs without crashing

**Screenshots**

Warning when loading:
```
AUDIT SUMMARY: ELW Pro Backgammon v3.06 Demo
AUDIT DETAIL: Copyright (C) 2008 Elwynor - www.elwynor.com
AUDIT SUMMARY: ELW Pro Backgammon 10 Demo Days Left
AUDIT DETAIL: Copyright (C) 2008 Elwynor - www.elwynor.com
2020-10-09 19:34:03.5590 Warn MBBSEmu.Btrieve.BtrieveFileProcessor.LoadBtrieveKeyDefinitions Btireve Log Key Present in ELWBKHI2.DAT
2020-10-09 19:34:03.5839 Warn MBBSEmu.Btrieve.BtrieveFileProcessor.GetByKeyFirstNumeric Unable to locate First record by key ELWBKGM2.DAT:2:2
2020-10-09 19:34:03.5839 Info MBBSEmu.HostProcess.MbbsHost.AddModule Module ELWBAK added!
```

Crash Error:
```
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unable to locate FFFF:047A')
   at MBBSEmu.Memory.MemoryCore.GetWord(UInt16 segment, UInt16 offset)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: Netrunner
- MBBSEmu Build: 100920-8

**Comment by enusbaum** [comment]
This is a missing ordinal for `NAMTMP`

It looks like it's taking a value from this struct and constructing a command string of sorts. We need to noodle out what this string is and if it's even needed (if it's a system value that's used only by the host software, MBBSEmu might not need it).

<img width="847" alt="Screen Shot 2020-10-23 at 3 31 32 PM" src="https://user-images.githubusercontent.com/1139047/97046133-ecd0d300-1544-11eb-83fc-5f3ac2d41fc5.png">

**Comment by tuday2** [comment]
v6 btrieve game, not designed for dos mbbs
