### ISSUE TITLE
[ELWEP] Empire of the Peasants - Module crashes on listing "O"ther players

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#180]
**Module Information**
* Identifier: ELWEP
* Module Name: Empire of the Peasants
* Version: 2.02

**Describe the bug**
Module crashes on listing "O"ther players

**To Reproduce**
1. Load Empire of the Peasants Module
2. Enter Module
3. Select "O" option from main menu (Other Players)

**Expected behavior**
Lists other players

**Screenshots**
```
Unhandled exception. System.Exception: Unsupported Btrieve Operation: GetLast
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.obtbtvl()
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

![EP](https://user-images.githubusercontent.com/27604078/95644954-1affde80-0a80-11eb-889c-73dcb90ab59b.JPG)

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: NetRunner
- MBBSEmu Build: 100920-8

**Comment by enusbaum** [comment]
`GetLast` should set the BTV Position to that of the last record and set the BTV Record Data to the value of the record. `obtbtvl` should return `0` if there were zero records in the BTV file and the seek failed.

**Comment by enusbaum** [comment]
@paladine Assigning this to you -- verifying `GetLast` is implemented in the SQLite branch as to not implement it in the JSON implementation only to deprecate it.

**Comment by tuday2** [comment]
v6 btrieve game, not designed for dos mbbs
