### ISSUE TITLE
[SFABLX] BLOX - Module crashes when resetting high scores

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#181]
**Module Information**
* Identifier: SFABLX
* Module Name: BLOX
* Version: 1.01

**Describe the bug**
Module crashes when resetting high scores

**To Reproduce**
1. Load Module
2. Enter Module
3. Select "R"eset High Scores

**Expected behavior**
High scores are reset

**Screenshots**
```
2020-10-10 07:25:41.0053 Error MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke Unknown Exported Function Ordinal in MAJORBBS: 211:FILELENGTH
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unknown Exported Function Ordinal in MAJORBBS: 211:FILELENGTH')
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: NetRunner
- MBBSEmu Build: 100920-8

**Comment by enusbaum** [comment]
Ordinal `MAJORBBS:211` is `FILELENGTH` -- `long filelength(int handle);`

We save the handles for the FileStream objects in a dictionary, so this Ordinal would require returning the `.Length` of the File Stream.
