### ISSUE TITLE
[EWEPNT] Phantasia - Crashes entering world - after character creation

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#192]
**Module Information**
* Identifier: EWEPNT
* Module Name: Phantasia
* Version: (C)1995

**Describe the bug**
Crashes entering world - after character creation

**To Reproduce**
1. Load Module
2. Enter Module
3. Create Character

**Expected behavior**
Ability to create character and enter world

**Screenshots**
```
2020-10-12 23:37:04.0631 Warn MBBSEmu.HostProcess.ExportedModules.Majorbbs.prfmsg prfmsg() unable to locate message number 1973 in current MCV file EWEPNT.MCV
Unhandled exception. System.Exception: Unsupported Btrieve Operation: GetLast
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.obtbtvl()
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()
```

![Screenshot 2020-10-07 223736-111](https://user-images.githubusercontent.com/27604078/95412079-bca2f680-08ed-11eb-89b8-7203a39e2544.jpg)

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: NetRunneer
- MBBSEmu Build: 101320-1

**Comment by tuday2** [comment]
Might be the same as #180  but logged as there is a prfmsg error that happens right before

Also this may help #31

**Comment by enusbaum** [comment]
Correct, this is the same as #180. I'll close this as a duplicate, we can log another defect for the unknown message number if we can identify it as an issue or an expected result.
