### ISSUE TITLE
[WCCMMUD] MajorMud - Crashes when attacking acid slime in Newhaven Arena

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#199]
**Module Information**
* Identifier: WCCMMUD
* Module Name: MajorMud
* Version: 1.11g

**Describe the bug**
Game crashes when attacked acid slime in Newhaven

**To Reproduce**
1. Enter MajorMud module
2. Navigate to Newhaven Arena
3. Enter combat with acid slime
4. See Error

**Expected behavior**
Ability to kill monsters in combat

**Screenshots**
```
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MBBSEmu.HostProcess.ExportedModules.ExportedModuleBase.FormatPrintf(ReadOnlySpan`1 stringToParse, UInt16 startingParameterOrdinal, Boolean isVsPrintf)
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.sprintf()
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

![Screenshot 2020-10-16 190547](https://user-images.githubusercontent.com/27604078/96323491-f1483980-0fe2-11eb-87f0-bf5c5313464c.jpg)

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: NetRunner
- MBBSEmu Build: 101620-3

**Comment by tuday2** [comment]
Haven't been able to reproduce -- closing until i see it again
