### ISSUE TITLE
[MBMGEMP] Galactic Empire - Crashes on startup

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#236]
**Module Information**
* Identifier: MBMGEMP
* Module Name: Galactic Empire
* Version: 3.2e

**Describe the bug**
Game crashes on startup of MBBSemu, similiar to issue #58 

**To Reproduce**
1. Add game to moduleConfig.json
2. Start MBBSEmu
3. See Error

**Expected behavior**
Game loads

**Screenshots**
```
2020-10-31 07:32:46.2120 Info MBBSEmu.Btrieve.BtrieveFileProcessor.LoadSqlite Opening sqlite DB D:\MbbsX64\modules\GEMPIRE\MBMGEPLT.DB
2020-10-31 07:32:46.2120 Info MBBSEmu.HostProcess.ExportedModules.Phapi.DosAllocRealSeg Allocating 64 in Real-Mode memory at 2007:0000
2020-10-31 07:32:46.2120 Info MBBSEmu.HostProcess.ExportedModules.Phapi.DosAllocRealSeg Allocating 665 in Real-Mode memory at 2008:0000
2020-10-31 07:32:46.2290 Info MBBSEmu.HostProcess.ExportedModules.Phapi.DosAllocRealSeg Allocating 31 in Real-Mode memory at 2009:0000
Critical Exception has occurred:
System.ArgumentException: Bad unsigned integer key length 6
   at MBBSEmu.Btrieve.BtrieveKey.KeyDataToSqliteObject(ReadOnlySpan`1 keyData)
   at MBBSEmu.Btrieve.BtrieveFileProcessor.Insert(Byte[] record)
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.dinsbtv()
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.insbtv()
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.CPU.CpuCore.Op_Call()
   at MBBSEmu.CPU.CpuCore.Tick()
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.AddModule(MbbsModule module)
   at MBBSEmu.HostProcess.MbbsHost.Start(List`1 moduleConfigurations)
   at MBBSEmu.Program.Run(String[] args)
```

**Software Information:**
- OS: Windows 2019 Server Standard
- Telnet Client: NetRunner
- MBBSEmu Build: 103120-13

**Comment by tuday2** [comment]
Fixed in Build 110120-4
