### ISSUE TITLE
[WCCMUD] Major Mud - Crashes if you hit enter on a blank stat value

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#242]
**Module Information**
* Identifier: WCCMMUD
* Module Name: MajorMud
* Version: 1.11g

**Describe the bug**
Crashes if you hit enter on a blank stat value

**To Reproduce**
1. Enter MajorMud module
2. Enter character creation
3. Blank out stat and hit enter
4. See Error

**Expected behavior**
FSD gives error on blank stat and you can correct

**Screenshots**
```
Unhandled exception. System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt32(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int32.Parse(String s)
   at MBBSEmu.HostProcess.HostRoutines.FsdRoutines.ValidateField(SessionBase session, FsdStatus fsdStatus)
   at MBBSEmu.HostProcess.HostRoutines.FsdRoutines.InFullScreenDisplay(SessionBase session)
   at MBBSEmu.HostProcess.HostRoutines.FsdRoutines.ProcessSessionState(SessionBase session, Dictionary`2 modules)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()
```
![FSDissue2](https://user-images.githubusercontent.com/27604078/97787302-304bc280-1b7f-11eb-918f-df6cc1ebaa03.jpg)

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: NetRunner
- MBBSEmu Build: 103120-15

**Comment by enusbaum** [comment]
Issue was caused by the switch in `FsdRoutes.cs` which evaluates an `int.Parse()` to determine if the value you entered in the MajorMUD character screen is above or below a given value. I added a case prior to those evaluations which checks for a `int.TryParse()` failure and displays an appropriate message.

![image](https://user-images.githubusercontent.com/1139047/97805289-30050300-1c23-11eb-9f16-c7ffd584e7cd.png)

PR Pending
