### ISSUE TITLE
[GALKYR] Kyrandia - Cannot re-enter module after creating character

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#244]
**Module Information**
* Identifier: GALKYR
* Module Name: Kyrandia
* Version: 7.00

**Describe the bug**
Cannot re-enter module after creating character

**To Reproduce**
1. Enter Module
2. Create character
3. Exit module
4. Re-enter module (now that you have a character)
5. See error

**Expected behavior**
Module loads your character and you can play again

**Screenshots**
```
2020-11-01 10:23:08.3287 Error MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke Unknown Exported Function Ordinal in MAJORBBS: 178:DSPMSG
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unknown Exported Function Ordinal in MAJORBBS: 178:DSPMSG')
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.CPU.CpuCore.Op_Call()
   at MBBSEmu.CPU.CpuCore.Tick()
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Software Information:**
- OS: Windows 2019 Server Standard
- Telnet Client: NetRunner
- MBBSEmu Build: 110120-4

**Comment by tuday2** [comment]
**DSPMSG**
Ordinal: 178

Signature: void dspmsg(msgno,parm1,parm2,parm3);

Description: Display Message based on ANSI flag
