### ISSUE TITLE
[DIALCHAT] Dial Chat - Crash when changing color in chat

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#264]
**Module Information**
* Identifier: DIALCHAT
* Module Name: DialChat
* Version: unknown 

**Describe the bug**
Crash when changing color in chat

**To Reproduce**
1. Enter DialChat module
2. Hit <TAB> to change chat color
3. See Error

**Expected behavior**
Able to chat in different ANSI colors

```
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unknown Exported Function Ordinal in GALGSBL: 62')
   at MBBSEmu.HostProcess.ExportedModules.Galgsbl.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.CPU.CpuCore.Op_Call()
   at MBBSEmu.CPU.CpuCore.Tick()
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()
```

**Software Information:**
- OS: Windows 2019 Server Standard
- Telnet Client: NetRunner
- MBBSEmu Build: 110720-2

**Comment by tuday2** [comment]
### _CHIINP
Ordinal: 62

Signature: void chiinp(int chan,char c);

Description: Character Input Utility

**Comment by enusbaum** [comment]
`CHIINP` simulates the input of a new character. This looks like you send it a `char` and it invokes `btuchi` if one is set.

**Comment by tuday2** [comment]
Ordinal 22 "BTUINP" seems similar -- and has the same signature , tried pointing to this but doesn't send the text in color -- more investigation needed

**_BTUINP**
Ordinal: 22
Signature: void chiinp(int chan,char c);
Description: Input from a channel (ASCIIZ string)
