### ISSUE TITLE
[XCLIBUR] Excalibur! - Crashes when sending in game mail to another user

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#278]
**Module Information**
* Identifier: XCLIBUR
* Module Name: Excalibur!
* Version: Unknown

**Describe the bug**
Crashes when sending in game mail to another user

**To Reproduce**
1. Enter module
2. Select "Dispatch mail to another user"
3. Enter username of user

**Expected behavior**
Able to send in game mail to another user

**Screenshots**
```
2020-11-08 22:54:14.3250 Error MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke Unknown Exported Function Ordinal in MAJORBBS: 88:OLDBGNEDT
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unknown Exported Function Ordinal in MAJORBBS: 88:OLDBGNEDT')
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.CPU.CpuCore.Op_Call()
   at MBBSEmu.CPU.CpuCore.Tick()
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()
```

**Software Information:**
- OS: Windows 2019 Server Standard
- Telnet Client: NetRunner
- MBBSEmu Build: 110920-7

**Comment by tuday2** [comment]
Dial Chat - This same error is happening when using /M command

**Comment by enusbaum** [comment]
Duplicate of #166

**Comment by enusbaum** [comment]
`BGNEDIT` and `OLDBGNEDIT` look like routines that start the email/message entry system. This differs from the FSD Entry screen as a template is not passed in, it's a standard message entry. 

We'll need to write a new subsystem that handles text entry similar to the MajorBBS/Worldgroup message entry screens.

**Comment by ftoledo** [comment]
> Dial Chat - This same error is happening when using /M command

I have this error if using the 625 version of DLL
