### ISSUE TITLE
[GWWARROW] Archery - Module fails to initialize

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#293]
**Module Information**
* Identifier: GWWARROW
* Module Name: Archery
* Version: 1.4

**Describe the bug**
Module fails to initialize

**To Reproduce**
1. Add to moduleConfig.json
2. Load MBBSEmu
3. See error

**Expected behavior**
Archery loads properly

**Screenshots**
```
2020-11-15 16:13:16.7132 Info MBBSEmu.Module.MsgFile..ctor Compiling MCV from GWWARROW.MSG
2020-11-15 16:13:16.7294 Info MBBSEmu.Module.MsgFile.BuildMCV Compiled GWWARROW.MCV (56 values, 12254 bytes)
2020-11-15 16:13:16.7294 Info MBBSEmu.Module.MbbsModule..ctor Located _INIT__: 0002:0000
2020-11-15 16:13:16.7294 Info MBBSEmu.HostProcess.MbbsHost.AddModule Adding Module GWWARROW...
2020-11-15 16:13:16.7294 Info MBBSEmu.HostProcess.MbbsHost.AddModule Segment 1 (424 bytes) loaded!
2020-11-15 16:13:16.7370 Info MBBSEmu.HostProcess.MbbsHost.AddModule Segment 2 (10917 bytes) loaded!
2020-11-15 16:13:16.7370 Info MBBSEmu.HostProcess.MbbsHost.AddModule Segment 3 (9612 bytes) loaded!
2020-11-15 16:13:16.7370 Info MBBSEmu.HostProcess.MbbsHost.AddModule Segment 4 (149 bytes) loaded!
2020-11-15 16:13:16.7370 Info MBBSEmu.HostProcess.MbbsHost.AddModule Segment 5 (0 bytes) loaded!
2020-11-15 16:13:16.7370 Warn MBBSEmu.Module.MbbsModule.Execute GWWARROW exhausted execution Units, creating additional
Critical Exception has occurred:
System.ArgumentException: Failed to load database D:\MbbsX64\modules\GWWARROW\GWWARROW.DAT: NO KEYS defined in D:\MbbsX64\modules\GWWARROW\GWWARROW.DAT
   at MBBSEmu.Btrieve.BtrieveFile.LoadFile(ILogger logger, String fullPath)
   at MBBSEmu.Btrieve.BtrieveFile.LoadFile(ILogger logger, String path, String fileName)
   at MBBSEmu.Btrieve.BtrieveFileProcessor..ctor(IFileUtility fileUtility, String path, String fileName)
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.opnbtv()
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.CPU.CpuCore.Op_Call()
   at MBBSEmu.CPU.CpuCore.Tick()
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.AddModule(MbbsModule module)
   at MBBSEmu.HostProcess.MbbsHost.Start(List`1 moduleConfigurations)
   at MBBSEmu.Program.Run(String[] args)
```

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: NetRunner
- MBBSEmu Build: 111220-2

**Comment by paladine** [comment]
There are no keys defined in this database, which is strange as most have at least one key.

**Comment by tuday2** [comment]
Fixed.
