### ISSUE TITLE
[LOGSAS] Swords & Sorcery - Crash when entering module

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#296]
**Module Information**
* Identifier: LOGSAS
* Module Name: Swords & Sorcery
* Version: 1.24

**Describe the bug**
Crash when entering module

**To Reproduce**
1. Add module to moduleConfig.json
2. Load MBBSEmu
3. Enter Module

**Expected behavior**
Ability to enter module

**Screenshots**
```
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MBBSEmu.Memory.MemoryCore.GetString(UInt16 segment, UInt16 offset, Boolean stripNull)
   at MBBSEmu.Memory.MemoryCore.GetString(IntPtr16 pointer, Boolean stripNull)
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.strlen()
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.CPU.CpuCore.Op_Call()
   at MBBSEmu.CPU.CpuCore.Tick()
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()
```

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: NetRunner
- MBBSEmu Build: 111220-2

**Comment by tuday2** [comment]
Fixed in build 112620-9
