### ISSUE TITLE
[GALSNV] SuperNova - Module crashes on entry

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#299]
**Module Information**
* Identifier: GALSNV
* Module Name: SuperNova
* Version: 1.0

**Describe the bug**
Module crashes on entry

**To Reproduce**
1. Add module to moduleConfig.json
2. Load MBBSEmu
3. Enter module

**Expected behavior**
Able to enter module

**Screenshots**
```
2020-11-16 22:34:28.1785 Error MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke Unknown Exported Function Ordinal in MAJORBBS: 137:CONDEX
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unknown Exported Function Ordinal in MAJORBBS: 137:CONDEX')
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.CPU.CpuCore.Op_Call()
   at MBBSEmu.CPU.CpuCore.Tick()
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()
```

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: NetRunner
- MBBSEmu Build: 111220-2

**Comment by tuday2** [comment]
Ordinal MAJORBBS.137 is condex() which specifies a conditional module exit.

**Comment by tuday2** [comment]
https://user-images.githubusercontent.com/27604078/97484416-b9b48800-1926-11eb-938b-c9b892460757.jpg

**Comment by enusbaum** [comment]
Ok -- so based on the documentation, `CONDEX()` basically lets you `return 0` from `sttrou()` anywhere in the stack, without having to roll all the way up to the top of the stack. 

The process to emulate here is checking if the `CONCEX` flag is set on the `usrprt->flags` ushort (`1<<11`). If the flag is set, halt the CPU by setting the `Registers.Halt` flag to `true` and return out. 

If `CONCEX` flag is not set, then just ignore the operation and continue.

**Comment by enusbaum** [comment]
OH -- and set the `usrptr->status` to `0` for the module, denoting an exit from sttrou.
