### ISSUE TITLE
[LOGSAS] Swords & Sorcery - Crashes when trying to move

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#312]
**Module Information**
* Identifier: LOGSAS
* Module Name: Swords & Sorcery
* Version: 1.24

**Describe the bug**
Crashes when trying to move

**To Reproduce**
1. Add module to moduleConfig.json
2. Load MBBSEmu
3. Enter Module
4. Create Character
5. Try to move 

**Expected behavior**
Ability to move rooms

**Screenshots**
```
2020-11-28 15:26:52.6647 Info MBBSEmu.HostProcess.ExportedModules.Galgsbl.btucmd Enable ANSI on channel 0 (Ignored)
2020-11-28 15:27:04.3706 Info MBBSEmu.HostProcess.ExportedModules.Galgsbl.btucmd Enable ANSI on channel 0 (Ignored)
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unknown Exported Function Ordinal in GALGSBL: 62')
   at MBBSEmu.HostProcess.ExportedModules.Galgsbl.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.CPU.CpuCore.Op_Call()
   at MBBSEmu.CPU.CpuCore.Tick()
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()
```

**Software Information:**
- OS: Windows Server 2019 Core
- Telnet Client: NetRunner
- MBBSEmu Build: 112620-9

**Comment by tuday2** [comment]
**_CHIINP**
Ordinal: 62
Signature: void chiinp(int chan,char c);
Description: Character Input Utility

**Comment by tuday2** [comment]
Same as #264
