### ISSUE TITLE
[SFAPGS] Progressive Slots - Fails to Initialize

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#341]
**Module Information**
* Identifier: SFAPGS
* Module Name: Progressive Slots
* Version: 1.00

**Describe the bug**
Fails to Initialize

**To Reproduce**
1. Add module to moduleConfig.json
2. Load MBBSEmu
3. See Error

**Expected behavior**
Ability to load module

**Screenshots**
```
2020-12-22 23:56:02.2855 Error MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke Unknown Exported Function Ordinal in MAJORBBS: 64:ALCDUP
Critical Exception has occurred:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unknown Exported Function Ordinal in MAJORBBS: 64:ALCDUP')
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.CPU.CpuCore.Op_Call()
   at MBBSEmu.CPU.CpuCore.Tick()
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.AddModule(MbbsModule module)
   at MBBSEmu.HostProcess.MbbsHost.Start(List`1 moduleConfigurations)
   at MBBSEmu.Program.Run(String[] args)
```

**Software Information:**
- OS: Windows Server 2019 Core
- Telnet Client: NetRunner
- MBBSEmu Build: 122220-1

**Comment by tuday2** [comment]
**ALCDUP**
Ordinal: 64
Signature: char *alcdup(char *stg);

Description: Allocate new space for a string

**Comment by tuday2** [comment]
It says its for 6.25->wg2 however when I created the alcdup ordinal and it's giving an error:

it is passing 9D31:1000 as the string pointer to copy to a new variable/memory and GetString is saying "Index was outside the bounds of the array"
