### ISSUE TITLE
MBBSEmu crashed when console telnet client session killed

### ISSUE THREAD

**Issue by ryanfantus** [enusbaum/MBBSEmu#37]
When killing a client telnet session, MBBSEmu fails with the following:

```
Unhandled exception. System.Exception: Invalid IAC?
   at MBBSEmu.Session.Telnet.TelnetSession.ParseIAC(ReadOnlySpan`1 iacResponse)
   at MBBSEmu.Session.Telnet.TelnetSession.ProcessIncomingClientData(Int32 bytesReceived)
   at MBBSEmu.Session.Telnet.TelnetSession.OnReceiveData(IAsyncResult asyncResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback()
   at System.Net.ContextAwareResult.<>c.<Complete>b__15_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.LazyAsyncResult.InvokeCallback(Object result)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionCallback(Int32 numBytes, SocketError errorCode)
   at System.Net.Sockets.OverlappedAsyncResult.CompletionCallback(Int32 numBytes, Byte[] socketAddress, Int32 socketAddressSize, SocketFlags receivedFlags, SocketError errorCode)
   at System.Net.Sockets.SocketAsyncContext.BufferMemoryReceiveOperation.InvokeCallback(Boolean allowPooling)
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.ProcessAsyncOperation(TOperation op)
   at System.Net.Sockets.SocketAsyncContext.ProcessAsyncReadOperation(ReadOperation op)
   at System.Net.Sockets.SocketAsyncContext.ReadOperation.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
Aborted (core dumped)
```

**Comment by enusbaum** [comment]
What Telnet client were you using when you connected to MBBSEmu?

**Comment by ryanfantus** [comment]
Just the traditional telnet client provided with inet tools in Ubuntu 20.04. I should mention I'm running this as a user, not as root, and running on ports which don't require any elevated permissions. Perhaps that's why I'm seeing this?

**Comment by enusbaum** [comment]
Confirmed for Linux command line telnet, if you're running MBBSEmu on a non-standard port (!= 23), Linux telnet will not negotiate IAC resulting in some weirdness.

To fix this run telnet via:

telnet -- <host>-<port>

---

Long term, we should probably gracefully handle invalid IAC codes by just logging them and then purging the invalid bytes from the buffer.
