### ISSUE TITLE
Crashes on long string length

### ISSUE THREAD

**Issue by dlightman311** [enusbaum/MBBSEmu#47]
Typing 30 characters at the Username prompt and pressing return at the Password prompt causes this crash (1):

Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at MBBSEmu.HostProcess.Structs.UserAccount.GetUserId()
   at MBBSEmu.HostProcess.HostRoutines.MenuRoutines.LoginPasswordInput(SessionBase session)
   at MBBSEmu.HostProcess.HostRoutines.MenuRoutines.ProcessSessionState(SessionBase session, Dictionary`2 modules)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   
Typing 60 characters at the Username prompt and pressing return causes this crash (2):   
   
Unhandled exception. System.ArgumentException: Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at MBBSEmu.HostProcess.Structs.UserAccount.SetUserId(String username)
   at MBBSEmu.HostProcess.HostRoutines.MenuRoutines.LoginUsernameInput(SessionBase session)
   at MBBSEmu.HostProcess.HostRoutines.MenuRoutines.ProcessSessionState(SessionBase session, Dictionary`2 modules)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

   Crash 2 is also reproducible at the username prompt during new user signup.

**Comment by enusbaum** [comment]
Closed with PR #79
