### ISSUE TITLE
[MHWWHL] Wheel of Fame! - Crashing on any command in game

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#53]
**Module Information**
* Identifier: MJWWHL
* Module Name: Wheel of Fame!
* Version: Unknown

**Describe the bug**
Module crashes on any input once you are playing a game

**To Reproduce**
Enter module - play game - Any input once in game will crash MBBSemu

**Expected behavior**
Game plays properly

**Screenshots**
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unknown Exported Function Ordinal in MAJORBBS: 579')
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.CPU.CpuCore.Tick()
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Software Information:**
 - OS: Windows 2019 Server Standard
- Telnet Client: Netrunner

**API REPORT**
{"UniqueIdentifier":"MJWWHL","File":"MJWWHL.DLL","Imports":{"DOSCALLS":[89],"PHAPI":[16],"MAJORBBS":[574,762,827,459,713,460,625,330,437,516,561,599,550,628,313,53,485,534,326,578,604,566,650,441,389,543,455,456,544,65,492,589,331,476,559,474,521,761,335,463,403,629,113,785,787,786,582,117,119,162,579,401,573,654,484,520,665,571,560,77,11,659,486,621,351,522,94,411,205,225,622,757,357,167],"GALGSBL":[40,63,72,59]}}

**Comment by enusbaum** [comment]
Fixed with https://github.com/enusbaum/MBBSEmu/pull/61

**Comment by tuday2** [comment]
Confirmed fixed.
