### ISSUE TITLE
[MBMGEMP] Galactic Empire - Crashes on startup

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#58]
**Module Information**
* Identifier: MBMGEMP
* Module Name: Galactic Empire
* Version: 3.2e

**Describe the bug**
Game crashes on startup of MBBSemu

**To Reproduce**
1.  Attempt to load game

**Expected behavior**
Game loads

**Screenshots**
```
2020-08-24 04:52:40.1280 Warn MBBSEmu.Module.MbbsModule.Execute MBMGEMP exhausted execution Units, creating additional
Critical Exception has occured:
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Int16.Parse(ReadOnlySpan`1 s, NumberStyles style, IFormatProvider provider)
   at MBBSEmu.Module.McvFile.GetNumeric(Int32 ordinal)
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.numopt()
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.CPU.CpuCore.Tick()
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.AddModule(MbbsModule module)
   at MBBSEmu.Program.Run(String[] args)
```

**Software Information:**
- OS: Windows 2019 Server Standard
- Telnet Client: NetRunner

**Comment by tuday2** [comment]
{"UniqueIdentifier":"MBMGEMP","File":"MBMGEMP.DLL","Imports":{"DOSCALLS":[89],"PHAPI":[32,49,16],"MAJORBBS":[11,737,226,43,441,650,659,389,566,94,520,456,492,589,331,559,437,654,658,133,455,544,65,604,107,543,469,602,522,313,53,485,534,463,628,476,624,335,434,417,516,484,162,134,601,560,409,574,429,430,435,582,621,656,113,629,474,117,119,565,444,170,577,77,225,205,210,625,350,401,550,403,511,603,167,462,267,266,578,349,460,352,593,510,505,475,712,428,581,459,468,665,657,661,348,449,377,399,486,55,351,400,366,411,230],"GALMSG":[30],"GALGSBL":[40,21,36,72]}}

**Comment by enusbaum** [comment]
This might have been fixed by #89 which better handles numeric values in MCV files that are preceded by ASCII characters, which this error appears to be. Please re-test and report back! 👍

**Comment by tuday2** [comment]
BUILD: 090320-8

**Different Error:**

Critical Exception has occurred:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unsupported OpCode: In')
   at MBBSEmu.CPU.CpuCore.Tick()
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.AddModule(MbbsModule module)
   at MBBSEmu.Program.Run(String[] args)

**Comment by enusbaum** [comment]
Looks like Galactic Empire has some pretty sophisticated methods for protected the key + keygen portions of the code, including inline Assembly to prevent debuggers from intercepting. 

https://github.com/bsimser/ge/blob/9bf8e3a2125b0a0b33cf3910c629da92214e091f/mbmgemp/SECURE.C#L431

The `PHAPI` Ordinals are also going to need implementing for memory reservations as well.

**Comment by enusbaum** [comment]
Ok! I was able to work through the PHAPI swamp and get Galactic Empire actually initializing in MBBSEmu. 

![image](https://user-images.githubusercontent.com/1139047/92636871-163fe300-f2a6-11ea-9e69-39c41610ad89.png)

![image](https://user-images.githubusercontent.com/1139047/92636881-19d36a00-f2a6-11ea-912f-4660ff2077c8.png)

I'm cleaning up the code right now but should have PR by tonight that'll close this issue 👍

**Comment by tuday2** [comment]
Same error as ELWGOLF @enusbaum @paladine  

```
2020-09-14 20:03:08.6741 Warn MBBSEmu.Module.MbbsModule.Execute MBMGEMP exhausted execution Units, creating additional
Critical Exception has occurred:
System.Exception: Type Requested not UInt16
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.AddModule(MbbsModule module)
   at MBBSEmu.Program.Run(String[] args)
```

**Comment by tuday2** [comment]
Not working in latest build
```
2020-10-31 07:32:46.2120 Info MBBSEmu.Btrieve.BtrieveFileProcessor.LoadSqlite Opening sqlite DB D:\MbbsX64\modules\GEMPIRE\MBMGEPLT.DB
2020-10-31 07:32:46.2120 Info MBBSEmu.HostProcess.ExportedModules.Phapi.DosAllocRealSeg Allocating 64 in Real-Mode memory at 2007:0000
2020-10-31 07:32:46.2120 Info MBBSEmu.HostProcess.ExportedModules.Phapi.DosAllocRealSeg Allocating 665 in Real-Mode memory at 2008:0000
2020-10-31 07:32:46.2290 Info MBBSEmu.HostProcess.ExportedModules.Phapi.DosAllocRealSeg Allocating 31 in Real-Mode memory at 2009:0000
Critical Exception has occurred:
System.ArgumentException: Bad unsigned integer key length 6
   at MBBSEmu.Btrieve.BtrieveKey.KeyDataToSqliteObject(ReadOnlySpan`1 keyData)
   at MBBSEmu.Btrieve.BtrieveFileProcessor.Insert(Byte[] record)
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.dinsbtv()
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.insbtv()
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.CPU.CpuCore.Op_Call()
   at MBBSEmu.CPU.CpuCore.Tick()
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.AddModule(MbbsModule module)
   at MBBSEmu.HostProcess.MbbsHost.Start(List`1 moduleConfigurations)
   at MBBSEmu.Program.Run(String[] args)
```
