### ISSUE TITLE
[SFAYTZ] Yahtzee - Crash on Exit

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#59]
**Module Information**
* Identifier: SFAYTZ
* Module Name: Yahtzee
* Version: Unknown

**Describe the bug**
Module crashes MBBSemu on exit

**To Reproduce**
Enter module - play game - upon exit it will crash MBBSEmu

**Expected behavior**
Exit properly

**Screenshots**
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unknown Exported Function Ordinal in MAJORBBS: 131')
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.CPU.CpuCore.Tick()
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()

**Software Information:**
 - OS: Windows 2019 Server Standard
- Telnet Client: Netrunner

**Comment by enusbaum** [comment]
Fixed with https://github.com/enusbaum/MBBSEmu/pull/61

**Comment by enusbaum** [comment]
Confirmed Fixed
