### ISSUE TITLE
[DIALCHAT] DialChat - /SM command crashes MBBSemu

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#71]
**Module Information**
* Identifier: DIALCHAT
* Module Name: DialChat
* Version: unknown 

**Describe the bug**
Using the /SM command causes MBBSEmu to crash

**To Reproduce**
1. Enter DIalChat module
2. Execute the "/SM" command to show members

**Expected behavior**
Lists members

**Screenshots**
![Annotation 2020-08-29 104104](https://user-images.githubusercontent.com/27604078/91642559-e82ee900-e9f1-11ea-846c-13bfd5818692.jpg)

```
MBBSEmu Log:
Unhandled exception. System.Exception: Unsupported Btrieve Query Option: 59
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.qrybtv()
   at MBBSEmu.HostProcess.ExportedModules.Majorbbs.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.CPU.CpuCore.Tick()
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Software Information:**
- OS: Windows 2019 Server Standard
- Telnet Client: NetRunner

**API Report**
{"UniqueIdentifier":"DIALCHAT","File":"dialchat.dll","Imports":{"DOSCALLS":[89],"PHAPI":[16],"MAJORBBS":[582,134,587,560,571,574,589,601,550,622,444,544,534,757,628,455,456,492,331,665,520,625,420,330,494,158,261,68,437,566,505,357,658,636,459,434,417,516,569,77,637,476,334,629,463,191,87,114,403,401,543,624,97,578,349,11,522,474,435,113,458,559,713,428,91,467,350,656,238,260,234,640,88,511,164,641,366,553,85,162,170,485,129,442,151,241,521,167,53,484,313,462,117,119,180,460,194,1040,244,249,252,263,242,568,55,783,785,787,786,579,121,122,131,573,413,205,210,225,584,654,486,562],"GALGSBL":[72,7,53,4,60,30,21,36,63,62,19,6,22,64]}}

**Comment by enusbaum** [comment]
59 is GetKeyGreaterThanOrEqual (50 == Key, 9 == Get Greater Than or Equal)

![image](https://user-images.githubusercontent.com/1139047/91642838-950e6380-e9fc-11ea-84a7-c6a4d2a310c9.png)

**Comment by tuday2** [comment]
This appears to be fixed -- @paladine did you implement this?
