### ISSUE TITLE
[GALQFM] Quest for Magic - Crashes upon entering character name

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#72]
**Module Information**
* Identifier: GALQFM
* Module Name: Quest for Magic
* Version: unknown

**Describe the bug**
Crashes upon entering character name when you first enter module

**To Reproduce**
1. Enter Module
2. Enter your name

**Expected behavior**
You enter the game world

**Screenshots**
![Annotation 2020-08-29 104105](https://user-images.githubusercontent.com/27604078/91644570-e28dcf00-ea02-11ea-9a1d-a53734d51276.jpg)

**MBBSEmu Log:**
```
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unable to locate FFFF:00A9')
   at MBBSEmu.Memory.MemoryCore.GetWord(UInt16 segment, UInt16 offset)
   at MBBSEmu.CPU.CpuCore.GetOperandValueUInt16(OpKind opKind, EnumOperandType operandType)
   at MBBSEmu.CPU.CpuCore.Tick()
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()
```

**Software Information:**
- OS: Windows 2019 Server Standard
- Telnet Client: NetRunner

**API REPORT:**
{"UniqueIdentifier":"GALQFM","File":"GALQFM.DLL","Imports":{"DOSCALLS":[89],"PHAPI":[16],"MAJORBBS":[520,403,476,11,169,401,468,578,604,579,629,463,628,444,624,487,474,534,543,68,437,455,441,566,456,492,589,331,574,544,713,459,726,351,485,117,162,654,621,317,659,340,335,603,573,522,402,559,511,550,516,113,571,420,167],"GALGSBL":[40,58,59]}}

**Comment by enusbaum** [comment]
Access to memory location `0xFFFF:0x00A9` would be `MAJORBBS.169` which is `int digalw;`

Specifies if Digits are allowed to be in User-ID's. We'll go ahead and just hard-code this to `1`
