### ISSUE TITLE
[TTIOLT] Oltima 2000 - Crashes when navigating menu

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#74]
**Module Information**
* Identifier: TTIOLT
* Module Name: Oltima 2000
* Version: unknown

**Describe the bug**
Game crashes when navigating initial menu

**To Reproduce**
1. Enter Module
2. Try to move around menu

**Expected behavior**
Ability to "Play" the game and navigate menu

**Screenshots**
![Annotation 2020-08-29 104106](https://user-images.githubusercontent.com/27604078/91645001-ffc49c80-ea06-11ea-987f-8e6eba3e6343.jpg)

```
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Unknown Exported Function Ordinal in GALGSBL: 22')
   at MBBSEmu.HostProcess.ExportedModules.Galgsbl.Invoke(UInt16 ordinal, Boolean offsetsOnly)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.ExternalFunctionDelegate(UInt16 ordinal, UInt16 functionOrdinal)
   at MBBSEmu.CPU.CpuCore.Tick()
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()
```

**Software Information:**
- OS: Windows Server 2019 Standard
- Telnet Client: NetRunner

**API Report**
{"UniqueIdentifier":"TTIOLT","File":"TTIOLT.DLL","Imports":{"DOSCALLS":[89],"PHAPI":[16],"MAJORBBS":[11,226,43,637,401,77,403,628,520,476,629,377,334,463,543,516,561,599,455,456,492,589,331,113,574,544,624,511,636,560,474,119,485,162,313,53,534,167,565,350,578,571,462,389,566,107,441,650,158,117,522,587,484,625,351,621,459,437,654,659,458,713,559,658,486,317,409,428,601,134,580,475,712,640,639,582,477,505,550,205,225],"GALGSBL":[11,21,30,6,36,19,22,39,60,72,56]}}

**Comment by enusbaum** [comment]
`GALGSBL.22` is `btuinp()` which handles input from the user channel.

![image](https://user-images.githubusercontent.com/1139047/91645198-212a8600-ea11-11ea-95b6-1a7874bcdb3b.png)
